import type { TopologyNode, TopologyEdge, TopologyGroup } from '../types/topology.schema'

const id = (nodeId: string) => nodeId.replace(/-/g, '_')

const TEMPLATES: Record<string, (node: TopologyNode) => string[]> = {
  elb: (n) => [
    `resource "aws_lb" "${id(n.nodeId)}" {`,
    `  name               = "${n.nodeId}"`,
    `  load_balancer_type = "application"`,
    `  internal           = false`,
    `  subnets            = [aws_subnet.public_a.id, aws_subnet.public_c.id]`,
    `  security_groups    = [aws_security_group.alb.id]`,
    `}`,
  ],
  ec2: (n) => [
    `resource "aws_instance" "${id(n.nodeId)}" {`,
    `  ami             = "ami-0c55b159cbfafe1f0"`,
    `  instance_type   = "t3.medium"`,
    `  subnet_id       = aws_subnet.private_a.id`,
    `  security_groups = [aws_security_group.app.id]`,
    `  tags = { Name = "${n.label}" }`,
    `}`,
  ],
  rds: (n) => [
    `resource "aws_db_instance" "${id(n.nodeId)}" {`,
    `  identifier        = "${n.nodeId}"`,
    `  engine            = "mysql"`,
    `  engine_version    = "8.0"`,
    `  instance_class    = "db.t3.medium"`,
    `  multi_az          = true`,
    `  username          = "admin"`,
    `  password          = var.db_password`,
    `  db_subnet_group_name = aws_db_subnet_group.main.name`,
    `  skip_final_snapshot  = false`,
    `}`,
  ],
  lambda: (n) => [
    `resource "aws_lambda_function" "${id(n.nodeId)}" {`,
    `  function_name = "${n.nodeId}"`,
    `  runtime       = "nodejs18.x"`,
    `  handler       = "index.handler"`,
    `  role          = aws_iam_role.lambda_exec.arn`,
    `  filename      = "function.zip"`,
    `  memory_size   = 1024`,
    `  timeout       = 30`,
    `}`,
  ],
  apigw: (n) => [
    `resource "aws_api_gateway_rest_api" "${id(n.nodeId)}" {`,
    `  name = "${n.nodeId}"`,
    `  endpoint_configuration { types = ["REGIONAL"] }`,
    `}`,
  ],
  eks: (n) => [
    `resource "aws_eks_cluster" "${id(n.nodeId)}" {`,
    `  name     = "${n.nodeId}"`,
    `  role_arn = aws_iam_role.eks.arn`,
    `  vpc_config {`,
    `    subnet_ids = [aws_subnet.private_a.id, aws_subnet.private_c.id]`,
    `  }`,
    `}`,
  ],
  ecs: (n) => [
    `resource "aws_ecs_cluster" "${id(n.nodeId)}" {`,
    `  name = "${n.nodeId}"`,
    `  setting { name = "containerInsights"; value = "enabled" }`,
    `}`,
  ],
  cloudwatch: (n) => [
    `resource "aws_cloudwatch_dashboard" "${id(n.nodeId)}" {`,
    `  dashboard_name = "${n.nodeId}"`,
    `  dashboard_body = jsonencode({ widgets = [] })`,
    `}`,
  ],
  route53: (n) => [
    `resource "aws_route53_zone" "${id(n.nodeId)}" {`,
    `  name = "tcare.example.com"`,
    `}`,
  ],
  nat: (n) => [
    `resource "aws_nat_gateway" "${id(n.nodeId)}" {`,
    `  allocation_id = aws_eip.${id(n.nodeId)}.id`,
    `  subnet_id     = aws_subnet.public_a.id`,
    `  tags = { Name = "${n.label}" }`,
    `}`,
    ``,
    `resource "aws_eip" "${id(n.nodeId)}" { domain = "vpc" }`,
  ],
  s3: (n) => [
    `resource "aws_s3_bucket" "${id(n.nodeId)}" {`,
    `  bucket = "${n.nodeId}-bucket"`,
    `  tags   = { Name = "${n.label}" }`,
    `}`,
  ],
  igw: (n) => [
    `resource "aws_internet_gateway" "${id(n.nodeId)}" {`,
    `  vpc_id = aws_vpc.main.id`,
    `  tags   = { Name = "${n.label}" }`,
    `}`,
  ],
}

export function generateTerraform(
  nodes: TopologyNode[],
  edges: TopologyEdge[],
  groups: TopologyGroup[] = [],
): string {
  const out: string[] = [
    '# Generated by ZeuX IaC Composer',
    '# T-Care Connect Platform · ap-northeast-2',
    '',
    'terraform {',
    '  required_providers {',
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "aws" {',
    '  region = "ap-northeast-2"',
    '}',
    '',
  ]

  if (groups.some(g => g.type === 'vpc')) {
    out.push(
      'resource "aws_vpc" "main" {',
      '  cidr_block           = "10.0.0.0/16"',
      '  enable_dns_hostnames = true',
      '  tags = { Name = "main-vpc" }',
      '}',
      '',
    )
  }

  for (const node of nodes) {
    const tmpl = TEMPLATES[node.type]
    if (tmpl) {
      out.push(...tmpl(node), '')
    }
  }

  if (edges.length > 0) {
    out.push('# ── Connections ──────────────────────────────────')
    for (const edge of edges) {
      const f = nodes.find(n => n.nodeId === edge.from)
      const t = nodes.find(n => n.nodeId === edge.to)
      if (f && t) out.push(`# ${f.label}  →  ${t.label}${edge.label ? `  (${edge.label})` : ''}`)
    }
  }

  return out.join('\n')
}
