import type { FinOpsRun } from '../types/finops.schema'
import { formatDate, formatKrw, formatUsd, resolveExecutiveReport } from './executiveReport'

function usd(v?: number | null): string {
  return formatUsd(v) === '—' ? '—' : formatUsd(v)
}

function krw(v?: number | null): string {
  return formatKrw(v) === '—' ? '—' : formatKrw(v)
}

/** Client-side 경영 보고서 Markdown (mock·오프라인 다운로드용). */
export function buildExecutiveReportMarkdown(run: FinOpsRun): string {
  const exec = resolveExecutiveReport(run)
  const sla = exec.sla_context
  const scope = exec.scope
  const funnel = exec.funnel
  const priority = exec.priority_summary
  const backlog = exec.prioritized_backlog ?? []
  const patterns = exec.pattern_rollup ?? []
  const blocked = exec.blocked_defer ?? []
  const total = exec.total_monthly_waste_usd ?? run.findings_snapshot?.total_monthly_waste_usd ?? 0

  const service = run.service_name ?? run.service_id
  const summary =
    exec.report_summary ||
    `Eligible ${funnel?.eligible ?? 0}건, 예상 절감 ${usd(total)}/월. ` +
      `Defer ${funnel?.defer ?? 0}건, Blocked ${funnel?.blocked ?? 0}건.`

  const lines: string[] = [
    `# FinOps 경영 보고서 — ${service}`,
    '',
    '| 항목 | 값 |',
    '|------|-----|',
    `| Tenant | \`${run.tenant_id}\` |`,
    `| Service | \`${service}\` |`,
    `| Schedule | \`${run.schedule_window ?? '—'}\` |`,
    `| Run ID | \`${run.run_id}\` |`,
    `| Status | **${run.status}** |`,
    `| 생성 시각 | ${formatDate(run.finished_at ?? run.created_at)} |`,
    '',
    '> MVP: 자동 실행 없음 — 본 문서는 권유·승인(HITL)용 제안서입니다.',
    '',
    '## 경영 요약',
    '',
    summary,
    '',
    '## 핵심 KPI',
    '',
    `- **예상 절감/월:** ${usd(total)}`,
    `- **P0 즉시 조치:** ${priority?.P0.count ?? 0}건 (${usd(priority?.P0.waste_usd)})`,
    `- **Eligible:** ${funnel?.eligible ?? 0}건`,
    `- **Defer / Blocked:** ${funnel?.defer ?? 0} / ${funnel?.blocked ?? 0}`,
    `- **월 예산:** ${krw(sla?.monthly_budget_krw)}`,
    '',
    '## 운영·SLA 맥락',
    '',
    `- 환경: ${sla?.environment ?? '—'}`,
    `- 리전: ${sla?.primary_region ?? '—'}`,
    `- 평가 기간: ${scope?.evaluation_days ?? '—'}일`,
    `- Prod 권유 차단: ${scope?.prod_recommend_block ? 'Y' : 'N'}`,
    `- 스코프 리전: ${(scope?.regions ?? []).join(', ') || '—'}`,
    '',
    '## 기회 퍼널',
    '',
    '| 단계 | 건수 |',
    '|------|------|',
    `| 탐지 Findings | ${funnel?.findings_total ?? 0} |`,
    `| 가드 적용 | ${funnel?.guarded_total ?? 0} |`,
    `| Eligible | ${funnel?.eligible ?? 0} |`,
    `| Defer | ${funnel?.defer ?? 0} |`,
    `| Blocked | ${funnel?.blocked ?? 0} |`,
    '',
  ]

  if (patterns.length) {
    lines.push('## 패턴별 절감 (Eligible)', '', '| 패턴 | 건수 | 절감/월 |', '|------|------|---------|')
    for (const p of patterns) {
      lines.push(`| \`${p.pattern_id}\` | ${p.count} | ${usd(p.waste_usd)} |`)
    }
    lines.push('')
  }

  if (backlog.length) {
    lines.push(
      '## 우선 조치 권유',
      '',
      '| 우선 | 패턴 | 리소스 | 권유 | 절감/월 | 신뢰도 |',
      '|------|------|--------|------|---------|--------|',
    )
    for (const item of backlog) {
      const conf = item.confidence_score != null ? `${Math.round(item.confidence_score * 100)}%` : '—'
      lines.push(
        `| **${item.priority_band ?? '—'}** | \`${item.pattern_id ?? '—'}\` | ` +
          `\`${item.resource_id}\` | ${item.recommended_action ?? '—'} | ${usd(item.monthly_waste_usd)} | ${conf} |`,
      )
    }
    lines.push('')
  }

  if (blocked.length) {
    lines.push('## 부록 — SLA 가드 (Defer / Blocked)', '')
    for (const item of blocked) {
      lines.push(
        `- \`${item.resource_id}\` **[${item.guard_status}]** ${item.guard_reason ?? ''} (${usd(item.monthly_waste_usd)})`,
      )
    }
    lines.push('')
  }

  if (run.approval_status) {
    lines.push(
      '## 승인 상태',
      '',
      `- Status: **${run.approval_status}**`,
      `- Reviewer: ${run.approval_reviewer ?? '—'}`,
      `- Comment: ${run.approval_comment ?? '—'}`,
      '',
    )
  }

  lines.push('---', '*Generated by ZeuX FinOps Agent*')
  return lines.join('\n')
}

export function downloadExecutiveReportMarkdown(run: FinOpsRun): void {
  const md = buildExecutiveReportMarkdown(run)
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const slug = (run.service_id || 'service').replace(/[^a-z0-9-]+/gi, '-')
  a.href = url
  a.download = `finops-${slug}-${run.run_id}.md`
  a.click()
  URL.revokeObjectURL(url)
}

/** 백엔드 API Markdown (MariaDB 연결 시). */
export async function fetchExecutiveReportMarkdown(runId: string): Promise<string> {
  const res = await fetch(`/api/finops/runs/${encodeURIComponent(runId)}/report.md`)
  if (!res.ok) throw new Error(`report.md ${res.status}`)
  return res.text()
}
